# Clonamos el repositorio para obtener los dataSet

In [ ]:
!git clone https://github.com/joanby/machinelearning-az.git

# Damos acceso a nuestro Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Test it

In [ ]:
!ls '/content/drive/My Drive' 

# Google colab tools

In [ ]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Plantilla de Pre Procesado - Datos Categóricos


# Cómo importar las librerías


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [2]:
dataset = pd.read_csv('Data.csv')
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
X = dataset.iloc[:, :-1].values #variable independiente tendra las columnas pais, salario y edad
y = dataset.iloc[:, 3].values #cariable dependiente tendra la columna purchased
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Codificar datos categóricos

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [11]:
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X[:,0]) #hemos convertido nuestros datos tipo string o categoricos a datos númericos usando
#la función LabelEncoder, y le aplicamos la conversion usando fit_transform. 
#se puede observar que francia tiene el codigo 0, españa el 2 y alemania el 1

[0 2 1 2 1 0 2 0 1 0]


In [13]:
#sin embargo no nos basta con convertirla a numeros, debemos convertirla a variable dummy, para ello
#se usa la funcion onehotencoder
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],    # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                         # Leave the rest of the columns untouched
)
X = np.array(ct.fit_transform(X), dtype=np.float)
print(X)

[[1.0e+00 0.0e+00 0.0e+00 4.4e+01 7.2e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 4.8e+04]
 [0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 6.1e+04]
 [0.0e+00 1.0e+00 0.0e+00 4.0e+01     nan]
 [1.0e+00 0.0e+00 0.0e+00 3.5e+01 5.8e+04]
 [0.0e+00 0.0e+00 1.0e+00     nan 5.2e+04]
 [1.0e+00 0.0e+00 0.0e+00 4.8e+01 7.9e+04]
 [0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]


C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11308\1326039758.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array(ct.fit_transform(X), dtype=np.float)


#onehotencoder = OneHotEncoder(categorical_features=[0])
#X = onehotencoder.fit_transform(X).toarray()

In [17]:
#para nuestra columna Y que posee los valores purchase también lo codificamos
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [15]:
print(X.shape)

(10, 5)


In [18]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [19]:
result = pd.DataFrame({'Column1': X[:, 0], 'Column2': X[:, 1],'Column3': X[:, 2], 'Age': X[:, 3],'Salary': X[:, 4],'Purchased': y[:]})
display(result)

Column1  Column2  Column3   Age   Salary  Purchased
0      1.0      0.0      0.0  44.0  72000.0          0
1      0.0      0.0      1.0  27.0  48000.0          1
2      0.0      1.0      0.0  30.0  54000.0          0
3      0.0      0.0      1.0  38.0  61000.0          0
4      0.0      1.0      0.0  40.0      NaN          1
5      1.0      0.0      0.0  35.0  58000.0          1
6      0.0      0.0      1.0   NaN  52000.0          0
7      1.0      0.0      0.0  48.0  79000.0          1
8      0.0      1.0      0.0  50.0  83000.0          0
9      1.0      0.0      0.0  37.0  67000.0          1