# Clonamos el repositorio para obtener los dataSet

In [ ]:
!git clone https://github.com/joanby/machinelearning-az.git

# Damos acceso a nuestro Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Test it

In [ ]:
!ls '/content/drive/My Drive' 

# Google colab tools

In [ ]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Plantilla de Pre Procesado

# Cómo importar las librerías


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [13]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values


In [14]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy="mean",verbose=0)
imputer = imputer.fit(X[:,1:3])

X[:,1:3] = imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


c:\Users\USUARIO\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\impute\_base.py:337: FutureWarning: The 'verbose' parameter was deprecated in version 1.1 and will be removed in 1.3. A warning will always be raised upon the removal of empty columns in the future version.
  warnings.warn(


In [15]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X[:,0])

[0 2 1 2 1 0 2 0 1 0]


In [17]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],    # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                         # Leave the rest of the columns untouched
)
X = np.array(ct.fit_transform(X), dtype=np.float)

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_7424\2054964772.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array(ct.fit_transform(X), dtype=np.float)


In [18]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

result = pd.DataFrame({'Column1': X[:, 0], 'Column2': X[:, 1],'Column3': X[:, 2], 'Age': X[:, 3],'Salary': X[:, 4],'Purchased': y[:]})
display(result)

Column1  Column2  Column3  Age     Salary  Purchased
0      0.0      1.0      0.0  0.0  44.000000          0
1      1.0      0.0      0.0  1.0  27.000000          1
2      1.0      0.0      1.0  0.0  30.000000          0
3      1.0      0.0      0.0  1.0  38.000000          0
4      1.0      0.0      1.0  0.0  40.000000          1
5      0.0      1.0      0.0  0.0  35.000000          1
6      1.0      0.0      0.0  1.0  38.777778          0
7      0.0      1.0      0.0  0.0  48.000000          1
8      1.0      0.0      1.0  0.0  50.000000          0
9      0.0      1.0      0.0  0.0  37.000000          1

# Dividir el data set en conjunto de entrenamiento y conjunto de testing


In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [21]:
from sklearn.preprocessing import StandardScaler, normalize

estandarización: operación que le resta la media a cualquier numero de la lista y lo divide entre la
desviasión estandar.

normalización: tomar la lista de los numeros, restarle el minimo y dividirlo entre el rango. Esto permite mantener a los números en un rango de 0 a 1

In [22]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
print(X_train)

[[ 1.         -1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [-1.          1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [ 1.         -1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [ 1.         -1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [-1.          1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [ 1.         -1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [-1.          1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [-1.          1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
